"""add updated_at to order

Revision ID: e5f314697c5a
Revises: f237ccd29b91
Create Date: 2026-05-17 19:08:11.094141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5f314697c5a'
down_revision: Union[str, Sequence[str], None] = 'f237ccd29b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('order_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('order_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # Cria o tipo enum primeiro se ainda não existir
    productcategory = sa.Enum('OTHERS', 'DRINK', 'FOOD', 'SWEET', name='productcategory')
    productcategory.create(op.get_bind(), checkfirst=True)

    # Converte a coluna com USING explícito
    op.execute('ALTER TABLE product ALTER COLUMN category TYPE productcategory USING category::productcategory')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.alter_column('product', 'category',
               existing_type=sa.Enum('OTHERS', 'DRINK', 'FOOD', 'SWEET', name='productcategory'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('product', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('product', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('order_item', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('order_item', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('order', 'updated_at')
    # ### end Alembic commands ###
