"""initial schema

Revision ID: f237ccd29b91
Revises: 
Create Date: 2026-05-17 18:22:57.594423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'f237ccd29b91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('product', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE product SET created_at = '2025-01-01 00:00:00' WHERE created_at IS NULL")
    op.alter_column('product', 'created_at', nullable=False)

    op.add_column('order_item', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_item', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE order_item SET created_at = '2025-01-01 00:00:00' WHERE created_at IS NULL")
    op.alter_column('order_item', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.alter_column('product', 'category',
               existing_type=sa.Enum('OTHERS', 'DRINK', 'FOOD', 'SWEET', name='productcategory'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_column('order_item', 'updated_at')
    op.drop_column('order_item', 'created_at')
    op.drop_column('order', 'updated_at')
    # ### end Alembic commands ###
